import { Product, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Tanques de Abastecimento', icon: 'Fuel', productCount: 8 },
  { id: '2', name: 'Máquinas Agrícolas', icon: 'Tractor', productCount: 12 },
  { id: '3', name: 'Caminhões', icon: 'Truck', productCount: 6 },
  { id: '4', name: 'Filtros Industriais', icon: 'Filter', productCount: 15 },
  { id: '5', name: 'Elementos Filtrantes', icon: 'Package', productCount: 20 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Tanque Executive',
    model: '550L',
    category: 'Tanques de Abastecimento',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/aca6b5b4-17c0-4bf1-a7d8-c9bee166b3eb.png'],
    description: 'Tanque de abastecimento Executive com capacidade de 550 litros, ideal para operações que exigem alta performance e durabilidade. Sistema de filtragem integrado para garantir a qualidade do diesel.',
    technicalSpecs: {
      capacity: '550 Litros',
      micronage: '10 Microns',
      flow: '60 L/min',
      autonomy: '9 horas',
      application: 'Tanques de abastecimento',
      dimensions: '1200 x 800 x 900 mm',
      weight: '85 kg',
    },
  },
  {
    id: '2',
    name: 'Tanque Titan',
    model: '550L',
    category: 'Tanques de Abastecimento',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/b7ec4c57-b0d3-4086-a849-930b48926c06.png'],
    description: 'Tanque Titan 550L com construção robusta e sistema de filtragem avançado. Perfeito para operações pesadas em ambientes agrícolas e industriais.',
    technicalSpecs: {
      capacity: '550 Litros',
      micronage: '5 Microns',
      flow: '70 L/min',
      autonomy: '8 horas',
      application: 'Tanques de abastecimento',
      dimensions: '1250 x 850 x 950 mm',
      weight: '92 kg',
    },
  },
  {
    id: '3',
    name: 'Filtro Diesel Premium',
    model: 'FDP-300',
    category: 'Filtros Industriais',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/7fda38a1-3767-4bf2-a1e0-d967cbc8ce6f.jpg'],
    description: 'Filtro de diesel de alta eficiência para máquinas agrícolas e industriais. Remove impurezas e água do combustível, garantindo melhor desempenho do motor.',
    technicalSpecs: {
      micronage: '2 Microns',
      flow: '100 L/min',
      application: 'Máquinas agrícolas e caminhões',
      dimensions: '300 x 150 x 150 mm',
      weight: '3.5 kg',
    },
  },
  {
    id: '4',
    name: 'Elemento Filtrante Universal',
    model: 'EFU-150',
    category: 'Elementos Filtrantes',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/41d5c31d-ef49-4add-84ff-1a96a7b82936.jpg'],
    description: 'Elemento filtrante de reposição universal, compatível com diversos modelos de filtros. Alta capacidade de retenção de partículas.',
    technicalSpecs: {
      micronage: '10 Microns',
      application: 'Filtros diversos',
      dimensions: '250 x 100 mm',
      weight: '0.8 kg',
    },
  },
  {
    id: '5',
    name: 'Sistema de Filtragem Completo',
    model: 'SFC-1000',
    category: 'Filtros Industriais',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/908de591-a621-424d-9a88-cd2f7900366b.jpg'],
    description: 'Sistema completo de filtragem para grandes volumes. Ideal para frotas e operações industriais de grande porte.',
    technicalSpecs: {
      capacity: '1000 Litros',
      micronage: '3 Microns',
      flow: '150 L/min',
      application: 'Industrial',
      dimensions: '1500 x 1000 x 1200 mm',
      weight: '150 kg',
    },
  },
  {
    id: '6',
    name: 'Filtro Agrícola Compacto',
    model: 'FAC-200',
    category: 'Máquinas Agrícolas',
    images: ['https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/407ff6b0-c41a-40d5-9197-63038ca70014.png'],
    description: 'Filtro compacto especialmente desenvolvido para máquinas agrícolas. Fácil instalação e manutenção.',
    technicalSpecs: {
      micronage: '5 Microns',
      flow: '80 L/min',
      application: 'Tratores e colheitadeiras',
      dimensions: '350 x 200 x 180 mm',
      weight: '4.2 kg',
    },
  },
];
